///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SubmissionCase_E2E
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Adverse_Other_Personal_Info recording.
    /// </summary>
    [TestModule("f71b6cb0-9e7a-4a72-beb1-ceb483f57a48", ModuleType.Recording, 1)]
    public partial class Adverse_Other_Personal_Info : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SubmissionCase_E2ERepository repository.
        /// </summary>
        public static SubmissionCase_E2ERepository repo = SubmissionCase_E2ERepository.Instance;

        static Adverse_Other_Personal_Info instance = new Adverse_Other_Personal_Info();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Adverse_Other_Personal_Info()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Adverse_Other_Personal_Info Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'OAT_PI_FirstName' with focus on 'ApplicationUnderTest.OAT_PI_FirstName'.", repo.ApplicationUnderTest.OAT_PI_FirstNameInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.OAT_PI_FirstName.PressKeys("OAT_PI_FirstName");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'OAT_PI_LastName' with focus on 'ApplicationUnderTest.OAT_PI_LastName'.", repo.ApplicationUnderTest.OAT_PI_LastNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.OAT_PI_LastName.PressKeys("OAT_PI_LastName");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'OAT_PI_Address1' with focus on 'ApplicationUnderTest.OAT_PI_Address1'.", repo.ApplicationUnderTest.OAT_PI_Address1Info, new RecordItemIndex(2));
            repo.ApplicationUnderTest.OAT_PI_Address1.PressKeys("OAT_PI_Address1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'OAT_PI_Address2' with focus on 'ApplicationUnderTest.OAT_PI_Address2'.", repo.ApplicationUnderTest.OAT_PI_Address2Info, new RecordItemIndex(3));
            repo.ApplicationUnderTest.OAT_PI_Address2.PressKeys("OAT_PI_Address2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'OAT_PI_City' with focus on 'ApplicationUnderTest.OAT_PI_City'.", repo.ApplicationUnderTest.OAT_PI_CityInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.OAT_PI_City.PressKeys("OAT_PI_City");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'AR' on item 'ApplicationUnderTest.OAT_PI_State'.", repo.ApplicationUnderTest.OAT_PI_StateInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.OAT_PI_State.Element.SetAttributeValue("TagValue", "AR");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '40001' with focus on 'ApplicationUnderTest.OAT_PI_Zip'.", repo.ApplicationUnderTest.OAT_PI_ZipInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.OAT_PI_Zip.PressKeys("40001");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.", new RecordItemIndex(8));
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(9));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'Business' on item 'ApplicationUnderTest.OAT_PI_UseType'.", repo.ApplicationUnderTest.OAT_PI_UseTypeInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.OAT_PI_UseType.Element.SetAttributeValue("TagValue", "Business");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'VOIP' on item 'ApplicationUnderTest.OAT_PI_PhoneType'.", repo.ApplicationUnderTest.OAT_PI_PhoneTypeInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.OAT_PI_PhoneType.Element.SetAttributeValue("TagValue", "VOIP");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'Skip Trace' on item 'ApplicationUnderTest.OAT_PI_Source'.", repo.ApplicationUnderTest.OAT_PI_SourceInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.OAT_PI_Source.Element.SetAttributeValue("TagValue", "Skip Trace");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '9500095007' with focus on 'ApplicationUnderTest.OAT_PI_PhoneNumber'.", repo.ApplicationUnderTest.OAT_PI_PhoneNumberInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.OAT_PI_PhoneNumber.PressKeys("9500095007");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.", new RecordItemIndex(14));
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(15));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
