///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SubmissionCase_E2E
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Adverse1_Driver_Insurance_Information recording.
    /// </summary>
    [TestModule("634d1a6d-2443-4de7-a76b-09cf1e83720b", ModuleType.Recording, 1)]
    public partial class Adverse1_Driver_Insurance_Information : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SubmissionCase_E2ERepository repository.
        /// </summary>
        public static SubmissionCase_E2ERepository repo = SubmissionCase_E2ERepository.Instance;

        static Adverse1_Driver_Insurance_Information instance = new Adverse1_Driver_Insurance_Information();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Adverse1_Driver_Insurance_Information()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Adverse1_Driver_Insurance_Information Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.InsuranceInformation' at 80;21.", repo.ApplicationUnderTest.InsuranceInformationInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.InsuranceInformation.Click("80;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'TRANSGUARD INSURANCE' on item 'ApplicationUnderTest.AD1_LI_CompanyName'.", repo.ApplicationUnderTest.AD1_LI_CompanyNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.AD1_LI_CompanyName.Element.SetAttributeValue("TagValue", "TRANSGUARD INSURANCE");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'AD1_PolicyNumber_1' with focus on 'ApplicationUnderTest.AD1_LI_PolicyNumber'.", repo.ApplicationUnderTest.AD1_LI_PolicyNumberInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.AD1_LI_PolicyNumber.PressKeys("AD1_PolicyNumber_1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.", new RecordItemIndex(3));
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(4));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'AD1_ClaimNumber_1' with focus on 'ApplicationUnderTest.AD1_LI_ClaimNumber'.", repo.ApplicationUnderTest.AD1_LI_ClaimNumberInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.AD1_LI_ClaimNumber.PressKeys("AD1_ClaimNumber_1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(6));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.", new RecordItemIndex(7));
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'AD1_LI_ContactName' with focus on 'ApplicationUnderTest.AD1_LI_ContactName'.", repo.ApplicationUnderTest.AD1_LI_ContactNameInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.AD1_LI_ContactName.PressKeys("AD1_LI_ContactName");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'CA' on item 'ApplicationUnderTest.AD1_LI_USStateCode'.", repo.ApplicationUnderTest.AD1_LI_USStateCodeInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.AD1_LI_USStateCode.Element.SetAttributeValue("TagValue", "CA");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.", new RecordItemIndex(10));
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'AD1_LI_Address1' with focus on 'ApplicationUnderTest.AD1_LI_Address1'.", repo.ApplicationUnderTest.AD1_LI_Address1Info, new RecordItemIndex(11));
            repo.ApplicationUnderTest.AD1_LI_Address1.PressKeys("AD1_LI_Address1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'AD1_LI_Address2' with focus on 'ApplicationUnderTest.AD1_LI_Address2'.", repo.ApplicationUnderTest.AD1_LI_Address2Info, new RecordItemIndex(12));
            repo.ApplicationUnderTest.AD1_LI_Address2.PressKeys("AD1_LI_Address2");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(13));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(14));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'AD1_LI_City' with focus on 'ApplicationUnderTest.AD1_LI_City'.", repo.ApplicationUnderTest.AD1_LI_CityInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.AD1_LI_City.PressKeys("AD1_LI_City");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '900019001' with focus on 'ApplicationUnderTest.AD1_LI_ZipCode'.", repo.ApplicationUnderTest.AD1_LI_ZipCodeInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.AD1_LI_ZipCode.PressKeys("900019001");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.", new RecordItemIndex(17));
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(18));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'Business' on item 'ApplicationUnderTest.AD1_LI_PhoneUseType'.", repo.ApplicationUnderTest.AD1_LI_PhoneUseTypeInfo, new RecordItemIndex(19));
            repo.ApplicationUnderTest.AD1_LI_PhoneUseType.Element.SetAttributeValue("TagValue", "Business");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'Cell' on item 'ApplicationUnderTest.AD1_LI_PhoneType'.", repo.ApplicationUnderTest.AD1_LI_PhoneTypeInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.AD1_LI_PhoneType.Element.SetAttributeValue("TagValue", "Cell");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'Skip Trace' on item 'ApplicationUnderTest.AD1_LI_PhoneSource'.", repo.ApplicationUnderTest.AD1_LI_PhoneSourceInfo, new RecordItemIndex(21));
            repo.ApplicationUnderTest.AD1_LI_PhoneSource.Element.SetAttributeValue("TagValue", "Skip Trace");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'ApplicationUnderTest.AD1_LI_PhoneSource'.", repo.ApplicationUnderTest.AD1_LI_PhoneSourceInfo, new RecordItemIndex(22));
            repo.ApplicationUnderTest.AD1_LI_PhoneSource.PressKeys("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '9500095001' with focus on 'ApplicationUnderTest.AD1_LI_PhoneNumber'.", repo.ApplicationUnderTest.AD1_LI_PhoneNumberInfo, new RecordItemIndex(23));
            repo.ApplicationUnderTest.AD1_LI_PhoneNumber.PressKeys("9500095001");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.", new RecordItemIndex(24));
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(25));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
