///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SubmissionCase_E2E
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InsuredDetails_Vehicle_Information recording.
    /// </summary>
    [TestModule("a83c2f1e-a2a6-4806-a724-e1e4a5c7de17", ModuleType.Recording, 1)]
    public partial class InsuredDetails_Vehicle_Information : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SubmissionCase_E2ERepository repository.
        /// </summary>
        public static SubmissionCase_E2ERepository repo = SubmissionCase_E2ERepository.Instance;

        static InsuredDetails_Vehicle_Information instance = new InsuredDetails_Vehicle_Information();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InsuredDetails_Vehicle_Information()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InsuredDetails_Vehicle_Information Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'ApplicationUnderTest.ID_VI_LabelTagYes1'", repo.ApplicationUnderTest.ID_VI_LabelTagYes1Info, new ActionTimeout(10000), new RecordItemIndex(0));
            repo.ApplicationUnderTest.ID_VI_LabelTagYes1Info.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ID_VI_LicensePlate' with focus on 'ApplicationUnderTest.ID_VI_LicensePlate'.", repo.ApplicationUnderTest.ID_VI_LicensePlateInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.ID_VI_LicensePlate.PressKeys("ID_VI_LicensePlate");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'MA' on item 'ApplicationUnderTest.ID_VI_LicensePlateState'.", repo.ApplicationUnderTest.ID_VI_LicensePlateStateInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.ID_VI_LicensePlateState.Element.SetAttributeValue("TagValue", "MA");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '2014' on item 'ApplicationUnderTest.ID_VD_Vin_Year'.", repo.ApplicationUnderTest.ID_VD_Vin_YearInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.ID_VD_Vin_Year.Element.SetAttributeValue("TagValue", "2014");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ID_VD_VIN_Make' at Center.", repo.ApplicationUnderTest.ID_VD_VIN_MakeInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.ID_VD_VIN_Make.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Volkswagen' with focus on 'ApplicationUnderTest.ID_VD_VIN_Make'.", repo.ApplicationUnderTest.ID_VD_VIN_MakeInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.ID_VD_VIN_Make.PressKeys("Volkswagen");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(6));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}'.", new RecordItemIndex(7));
            Keyboard.Press("{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.ID_VD_VIN_Make_Volkswagen' at Center.", repo.ApplicationUnderTest.ID_VD_VIN_Make_VolkswagenInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.ID_VD_VIN_Make_Volkswagen.DoubleClick();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.", new RecordItemIndex(9));
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(10));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Submit_5' at 40;14.", repo.ApplicationUnderTest.Submit_5Info, new RecordItemIndex(11));
            repo.ApplicationUnderTest.Submit_5.Click("40;14");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
