///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SubmissionCase_E2E
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InsuredDetails_Company_Information recording.
    /// </summary>
    [TestModule("374c9e88-7249-446b-b73a-40d27a5542f6", ModuleType.Recording, 1)]
    public partial class InsuredDetails_Company_Information : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SubmissionCase_E2ERepository repository.
        /// </summary>
        public static SubmissionCase_E2ERepository repo = SubmissionCase_E2ERepository.Instance;

        static InsuredDetails_Company_Information instance = new InsuredDetails_Company_Information();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InsuredDetails_Company_Information()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InsuredDetails_Company_Information Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'NATIONAL UNITY INSURANCE CO' on item 'ApplicationUnderTest.ID_CI_CompName'.", repo.ApplicationUnderTest.ID_CI_CompNameInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.ID_CI_CompName.Element.SetAttributeValue("TagValue", "NATIONAL UNITY INSURANCE CO");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ID_CI_PolicyNumber' with focus on 'ApplicationUnderTest.ID_CI_PolicyNumber'.", repo.ApplicationUnderTest.ID_CI_PolicyNumberInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.ID_CI_PolicyNumber.PressKeys("ID_CI_PolicyNumber");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.", new RecordItemIndex(2));
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(3));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ID_CI_ClaimNumber' with focus on 'ApplicationUnderTest.ID_CI_ClaimNumber'.", repo.ApplicationUnderTest.ID_CI_ClaimNumberInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.ID_CI_ClaimNumber.PressKeys("ID_CI_ClaimNumber");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.", new RecordItemIndex(5));
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(6));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ID_CI_ContactNumber' with focus on 'ApplicationUnderTest.ID_CI_ContactNumber'.", repo.ApplicationUnderTest.ID_CI_ContactNumberInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.ID_CI_ContactNumber.PressKeys("ID_CI_ContactNumber");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'OH' on item 'ApplicationUnderTest.ID_CI_State'.", repo.ApplicationUnderTest.ID_CI_StateInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.ID_CI_State.Element.SetAttributeValue("TagValue", "OH");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ID_CI_Address1' with focus on 'ApplicationUnderTest.ID_CI_Address1'.", repo.ApplicationUnderTest.ID_CI_Address1Info, new RecordItemIndex(9));
            repo.ApplicationUnderTest.ID_CI_Address1.PressKeys("ID_CI_Address1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ID_CI_Address2' with focus on 'ApplicationUnderTest.ID_CI_Address2'.", repo.ApplicationUnderTest.ID_CI_Address2Info, new RecordItemIndex(10));
            repo.ApplicationUnderTest.ID_CI_Address2.PressKeys("ID_CI_Address2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ID_CI_City' with focus on 'ApplicationUnderTest.ID_CI_City'.", repo.ApplicationUnderTest.ID_CI_CityInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.ID_CI_City.PressKeys("ID_CI_City");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '40006' with focus on 'ApplicationUnderTest.ID_CI_Zip'.", repo.ApplicationUnderTest.ID_CI_ZipInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.ID_CI_Zip.PressKeys("40006");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(13));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.", new RecordItemIndex(14));
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(15));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'Business' on item 'ApplicationUnderTest.ID_CI_UseType'.", repo.ApplicationUnderTest.ID_CI_UseTypeInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.ID_CI_UseType.Element.SetAttributeValue("TagValue", "Business");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'Cell' on item 'ApplicationUnderTest.ID_CI_PhoneType'.", repo.ApplicationUnderTest.ID_CI_PhoneTypeInfo, new RecordItemIndex(17));
            repo.ApplicationUnderTest.ID_CI_PhoneType.Element.SetAttributeValue("TagValue", "Cell");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'Caller ID' on item 'ApplicationUnderTest.ID_CI_Source'.", repo.ApplicationUnderTest.ID_CI_SourceInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.ID_CI_Source.Element.SetAttributeValue("TagValue", "Caller ID");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '9500095012' with focus on 'ApplicationUnderTest.ID_CI_PhoneNumber'.", repo.ApplicationUnderTest.ID_CI_PhoneNumberInfo, new RecordItemIndex(19));
            repo.ApplicationUnderTest.ID_CI_PhoneNumber.PressKeys("9500095012");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(20));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Submit_5' at 52;15.", repo.ApplicationUnderTest.Submit_5Info, new RecordItemIndex(21));
            repo.ApplicationUnderTest.Submit_5.Click("52;15");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
