///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SubmissionCase_E2E
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InsuredDetails_Attorney_Information recording.
    /// </summary>
    [TestModule("5bc21814-3a7d-477f-b47a-b188fd606eec", ModuleType.Recording, 1)]
    public partial class InsuredDetails_Attorney_Information : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SubmissionCase_E2ERepository repository.
        /// </summary>
        public static SubmissionCase_E2ERepository repo = SubmissionCase_E2ERepository.Instance;

        static InsuredDetails_Attorney_Information instance = new InsuredDetails_Attorney_Information();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InsuredDetails_Attorney_Information()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InsuredDetails_Attorney_Information Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ID_AI_FirmName' with focus on 'ApplicationUnderTest.ID_AI_FirmName'.", repo.ApplicationUnderTest.ID_AI_FirmNameInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.ID_AI_FirmName.PressKeys("ID_AI_FirmName");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ID_AI_FirstName' with focus on 'ApplicationUnderTest.ID_AI_FirstName'.", repo.ApplicationUnderTest.ID_AI_FirstNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.ID_AI_FirstName.PressKeys("ID_AI_FirstName");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ID_AI_LastName' with focus on 'ApplicationUnderTest.ID_AI_LastName'.", repo.ApplicationUnderTest.ID_AI_LastNameInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.ID_AI_LastName.PressKeys("ID_AI_LastName");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ID_AI_Address1' with focus on 'ApplicationUnderTest.ID_AI_Address1'.", repo.ApplicationUnderTest.ID_AI_Address1Info, new RecordItemIndex(3));
            repo.ApplicationUnderTest.ID_AI_Address1.PressKeys("ID_AI_Address1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ID_AI_Address2' with focus on 'ApplicationUnderTest.ID_AI_Address2'.", repo.ApplicationUnderTest.ID_AI_Address2Info, new RecordItemIndex(4));
            repo.ApplicationUnderTest.ID_AI_Address2.PressKeys("ID_AI_Address2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ID_AI_City' with focus on 'ApplicationUnderTest.ID_AI_City'.", repo.ApplicationUnderTest.ID_AI_CityInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.ID_AI_City.PressKeys("ID_AI_City");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'CT' on item 'ApplicationUnderTest.ID_AI_State'.", repo.ApplicationUnderTest.ID_AI_StateInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.ID_AI_State.Element.SetAttributeValue("TagValue", "CT");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(7));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '32132' with focus on 'ApplicationUnderTest.ID_AI_Zipcode'.", repo.ApplicationUnderTest.ID_AI_ZipcodeInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.ID_AI_Zipcode.PressKeys("32132");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(9));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'attorney4@gmail.com' with focus on 'ApplicationUnderTest.ID_AI_Email'.", repo.ApplicationUnderTest.ID_AI_EmailInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.ID_AI_Email.PressKeys("attorney4@gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '06/04/2019' on item 'ApplicationUnderTest.ID_AI_RepresentationDate'.", repo.ApplicationUnderTest.ID_AI_RepresentationDateInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.ID_AI_RepresentationDate.Element.SetAttributeValue("TagValue", "06/04/2019");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.", new RecordItemIndex(12));
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.", new RecordItemIndex(13));
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(14));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'Personal' on item 'ApplicationUnderTest.ID_AI_UseType'.", repo.ApplicationUnderTest.ID_AI_UseTypeInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.ID_AI_UseType.Element.SetAttributeValue("TagValue", "Personal");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'Cell' on item 'ApplicationUnderTest.ID_AI_PhoneType'.", repo.ApplicationUnderTest.ID_AI_PhoneTypeInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.ID_AI_PhoneType.Element.SetAttributeValue("TagValue", "Cell");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'Caller ID' on item 'ApplicationUnderTest.ID_AI_Source'.", repo.ApplicationUnderTest.ID_AI_SourceInfo, new RecordItemIndex(17));
            repo.ApplicationUnderTest.ID_AI_Source.Element.SetAttributeValue("TagValue", "Caller ID");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '9500095012' with focus on 'ApplicationUnderTest.ID_AI_Phone'.", repo.ApplicationUnderTest.ID_AI_PhoneInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.ID_AI_Phone.PressKeys("9500095012");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(19));
            
            try {
                Report.Log(ReportLevel.Info, "Keyboard", "(Optional Action)\r\nKey sequence '{Tab}'.", new RecordItemIndex(20));
                Keyboard.Press("{Tab}");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(20)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SubmitButton1' at 46;15.", repo.ApplicationUnderTest.SubmitButton1Info, new RecordItemIndex(21));
            repo.ApplicationUnderTest.SubmitButton1.Click("46;15");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
