///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SubmissionCase_E2E
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("0e85b462-29d5-48e6-8a84-d307e397412a", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SubmissionCase_E2ERepository repository.
        /// </summary>
        public static SubmissionCase_E2ERepository repo = SubmissionCase_E2ERepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
            A_UserName = "";
            A_Password = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

        string _A_UserName;

        /// <summary>
        /// Gets or sets the value of variable A_UserName.
        /// </summary>
        [TestVariable("040ca9e3-1044-4526-b735-4f27dc8263dc")]
        public string A_UserName
        {
            get { return _A_UserName; }
            set { _A_UserName = value; }
        }

        string _A_Password;

        /// <summary>
        /// Gets or sets the value of variable A_Password.
        /// </summary>
        [TestVariable("83d55899-df84-4233-8f35-c6b2ade61e31")]
        public string A_Password
        {
            get { return _A_Password; }
            set { _A_Password = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtUserID' at 51;35.", repo.ApplicationUnderTest.TxtUserIDInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.TxtUserID.Click("51;35");
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$A_UserName' on item 'ApplicationUnderTest.TxtUserID'.", repo.ApplicationUnderTest.TxtUserIDInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.TxtUserID.Element.SetAttributeValue("TagValue", A_UserName);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ContentContainer' at 1104;100.", repo.ApplicationUnderTest.ContentContainerInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.ContentContainer.Click("1104;100");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtPassword' at 146;32.", repo.ApplicationUnderTest.TxtPasswordInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.TxtPassword.Click("146;32");
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$A_Password' on item 'ApplicationUnderTest.TxtPassword'.", repo.ApplicationUnderTest.TxtPasswordInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.TxtPassword.Element.SetAttributeValue("TagValue", A_Password);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ButtonTagSub' at 208;14.", repo.ApplicationUnderTest.ButtonTagSubInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.ButtonTagSub.Click("208;14");
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(6));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
