///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SubmissionCase_E2E
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Review_ClaimInformation_Page recording.
    /// </summary>
    [TestModule("05d627ea-34b3-4488-a2aa-525950474579", ModuleType.Recording, 1)]
    public partial class Review_ClaimInformation_Page : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SubmissionCase_E2ERepository repository.
        /// </summary>
        public static SubmissionCase_E2ERepository repo = SubmissionCase_E2ERepository.Instance;

        static Review_ClaimInformation_Page instance = new Review_ClaimInformation_Page();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Review_ClaimInformation_Page()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Review_ClaimInformation_Page Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ApplicationUnderTest.ReviewSubmissionInformationBelow'", repo.ApplicationUnderTest.ReviewSubmissionInformationBelowInfo, new ActionTimeout(30000), new RecordItemIndex(1));
            repo.ApplicationUnderTest.ReviewSubmissionInformationBelowInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Review Claim Information') on item 'ApplicationUnderTest.ReviewSubmissionInformationBelow'.", repo.ApplicationUnderTest.ReviewSubmissionInformationBelowInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.ReviewSubmissionInformationBelowInfo, "InnerText", "Review Claim Information");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Submit_Review' at Center.", repo.ApplicationUnderTest.Submit_ReviewInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Submit_Review.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ApplicationUnderTest.Actions_Button'", repo.ApplicationUnderTest.Actions_ButtonInfo, new ActionTimeout(30000), new RecordItemIndex(4));
            repo.ApplicationUnderTest.Actions_ButtonInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Resolved-Completed') on item 'ApplicationUnderTest.CaseStatus_Resolved_Completed'.", repo.ApplicationUnderTest.CaseStatus_Resolved_CompletedInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ApplicationUnderTest.CaseStatus_Resolved_CompletedInfo, "InnerText", "Resolved-Completed");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
